# Taskfile for hypyr homelab
# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: hypyr-homelab

includes:
  ansible: .taskfiles/ansible
  tofu: .taskfiles/opentofu
  komodo: .taskfiles/komodo
  swarm: .taskfiles/swarm

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  bootstrap:
    desc: Bootstrap local development environment
    cmds:
      - echo "Installing mise tools..."
      - mise install
      - 'echo "OK: Tools installed"'
      - echo ""
      - echo "Installing Ansible Galaxy dependencies..."
      - task: ansible:deps
      - echo ""
      - echo "Bootstrap complete. Run 'task validate' to verify."

  validate:
    desc: Run all validation checks
    deps:
      - validate:governance
      - validate:tools
      - validate:structure
      - validate:compose

  validate:governance:
    desc: Validate governance compliance
    cmds:
      - echo "Checking governance structure..."
      - test -f constitution/constitution.md
      - test -f contracts/hard-stops.md
      - test -f contracts/invariants.md
      - 'echo "OK: Governance files present"'

  validate:tools:
    desc: Validate required tools are available
    cmds:
      - mise doctor
      - 'echo "OK: Tools validated"'

  validate:structure:
    desc: Validate repository root structure
    cmds:
      - |
        if ! command -v conftest &> /dev/null; then
          echo "Conftest not found. Run: task bootstrap"
          exit 1
        fi
      - ./scripts/enforce-root-structure.sh

  validate:compose:
    desc: Validate all Docker Compose files
    cmds:
      - |
        echo "Validating Compose files..."
        failed=0
        for f in $(find stacks -name 'compose.yaml' -o -name 'compose.yml' -o -name 'docker-compose.yaml' -o -name 'docker-compose.yml' 2>/dev/null); do
          if docker compose -f "$f" config --quiet 2>/dev/null; then
            echo "  OK: $f"
          else
            echo "  FAIL: $f"
            failed=1
          fi
        done
        if [ $failed -eq 1 ]; then
          echo "Some Compose files failed validation"
          exit 1
        fi
        echo "OK: All Compose files valid"

  validate:tofu:
    desc: Validate OpenTofu configuration
    cmds:
      - task: tofu:validate

  status:
    desc: Quick status of entire infrastructure
    cmds:
      - echo "==> Ansible — Node Connectivity"
      - task: ansible:ping
      - echo ""
      - echo "==> Docker Swarm — Health"
      - task: swarm:health

  docs:
    desc: Generate/update documentation
    cmds:
      - echo "Documentation tasks TBD"

  clean:
    desc: Clean temporary files
    cmds:
      - echo "Cleaning temporary files..."
      - rm -rf .task/
      - echo "Clean complete"
