# Media Secrets Contract: 1Password Items and Templates
# Defines the secret management requirements for media stacks
#
# Spec: 007-media-stack-migration
# ADR: ADR-0035 (secret hydration pattern)

---
apiVersion: v1
kind: MediaSecretsContract
metadata:
  name: media-secret-hydration
  spec: "007-media-stack-migration"
  adr: ADR-0035

# 1Password Items Required
items:
  - name: plex-stack
    vault: homelab
    status: create_new
    fields:
      - name: claim_token
        type: password
        description: Plex claim token from plex.tv/claim (expires in 4 minutes)
        notes: Generate immediately before first deployment; not needed after initial claim

  - name: sonarr
    vault: homelab
    status: existing
    fields:
      - name: api_key
        type: password
        description: Sonarr API key (generated on first boot)
        notes: Populate after first deployment from Settings > General > API Key

  - name: radarr
    vault: homelab
    status: existing
    fields:
      - name: api_key
        type: password
        description: Radarr API key (generated on first boot)
        notes: Populate after first deployment from Settings > General > API Key

  - name: prowlarr
    vault: homelab
    status: existing
    fields:
      - name: api_key
        type: password
        description: Prowlarr API key (generated on first boot)
        notes: Populate after first deployment from Settings > General > API Key

  - name: sabnzbd
    vault: homelab
    status: existing
    fields:
      - name: api_key
        type: password
        description: SABnzbd API key (generated on first boot)
        notes: Populate after first deployment from Config > General > API Key

  - name: autobrr
    vault: homelab
    status: existing
    stack: torrent (deferred)
    fields:
      - name: api_key
        type: password
        description: Autobrr API key
      - name: session_secret
        type: password
        description: Session encryption secret

  - name: recyclarr
    vault: homelab
    status: existing
    stack: torrent (deferred)
    fields:
      - name: api_key
        type: password
        description: Recyclarr API key for Sonarr/Radarr sync

# Template Files
templates:
  - name: media.env.template
    stack: application_media_core
    path: stacks/application/media/core/media.env.template
    output: /mnt/apps01/appdata/media/core/secrets/media.env
    references:
      - "PLEX_CLAIM=op://homelab/plex-stack/claim_token"
      - "SONARR_API_KEY=op://homelab/sonarr/api_key"
      - "RADARR_API_KEY=op://homelab/radarr/api_key"
      - "PROWLARR_API_KEY=op://homelab/prowlarr/api_key"
      - "SABNZBD_API_KEY=op://homelab/sabnzbd/api_key"

  - name: torrent.env.template
    stack: application_media_torrent
    path: stacks/application/media/torrent/torrent.env.template
    output: /mnt/apps01/appdata/media/torrent/secrets/torrent.env
    status: deferred
    references:
      - "AUTOBRR_API_KEY=op://homelab/autobrr/api_key"
      - "AUTOBRR_SESSION_SECRET=op://homelab/autobrr/session_secret"
      - "RECYCLARR_API_KEY=op://homelab/recyclarr/api_key"

# Hydration Job Configuration (per ADR-0035)
hydration_job:
  image: 1password/op:2
  digest: required  # Pin to SHA-256 digest
  deploy:
    mode: replicated-job
    restart_policy:
      condition: none
    resources:
      limits:
        cpus: "0.5"
        memory: "256M"
  environment:
    OP_CONNECT_HOST: http://op-connect-api:8080
    OP_CONNECT_TOKEN_FILE: /run/secrets/op_connect_token
  secrets:
    - op_connect_token (external: true)
  networks:
    - op-connect_op-connect (external: true)

# Validation Rules
validation:
  - rule: All 1Password items MUST exist before stack deployment
    check: "op item get {item_name} --vault homelab"

  - rule: Template files MUST only contain op:// references (no plaintext secrets)
    check: "grep -v '^#' {template} | grep -v 'op://' | grep '=' should return empty"

  - rule: Hydration job MUST complete successfully before dependent services start
    check: "docker service ls --filter name={stack}_op-secrets shows 0/1 (1/1 completed)"

  - rule: Output files MUST have permissions 644
    check: "stat -c '%a' {output_path} returns 644"
