apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-node-local-for-critical-data
  annotations:
    policies.kyverno.io/title: Deny Node-Local for Critical Data
    policies.kyverno.io/category: Storage
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: PersistentVolumeClaim
    policies.kyverno.io/description: >-
      Prevents using node-local storage class for non-ephemeral workloads.
      Use node-local only for scratch/cache/temp; prefer longhorn-replicated or
      NAS-backed classes for anything else.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: block-node-local-non-ephemeral
      match:
        any:
          - resources:
              kinds:
                - PersistentVolumeClaim
      preconditions:
        all:
          - key: "{{ request.object.spec.storageClassName || '' }}"
            operator: Equals
            value: node-local
      validate:
        message: "node-local storage is for ephemeral/scratch only. Use longhorn-replicated or NAS-backed class for persistent data."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.dataSourceRef || request.object.spec.dataSource || {} }}"
                operator: NotEquals
                value: {}
              - key: "{{ request.object.spec.volumeMode || 'Filesystem' }}"
                operator: NotEquals
                value: Filesystem
              - key: "{{ request.object.metadata.annotations.\"storage.hypyr.space/ephemeral\" || 'false' }}"
                operator: NotEquals
                value: "true"
