apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-rwx-access-mode
  annotations:
    policies.kyverno.io/title: Restrict ReadWriteMany Access Mode on Longhorn
    policies.kyverno.io/category: Storage
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: PersistentVolumeClaim
    policies.kyverno.io/description: >-
      Prevents PVCs from using ReadWriteMany (RWX) access mode with Longhorn storage
      classes unless explicitly approved. Longhorn does not natively support RWX and
      requires NFSv4 provisioner overlay, which adds complexity and failure modes.
    hypyr.space/rationale: "https://github.com/cpritchett/homelab/blob/main/requirements/storage/spec.md"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: deny-rwx-longhorn-without-approval
      match:
        any:
          - resources:
              kinds:
                - PersistentVolumeClaim
      preconditions:
        all:
          # Only apply to Longhorn storage classes
          - key: "{{ request.object.spec.storageClassName }}"
            operator: AnyIn
            value:
              - longhorn
              - longhorn-static
              - longhorn-rwx
          # Only trigger if RWX is requested
          - key: ReadWriteMany
            operator: AnyIn
            value: "{{ request.object.spec.accessModes }}"
      validate:
        message: >-
          PVC "{{ request.object.metadata.name }}" requests ReadWriteMany access mode
          with Longhorn storage class "{{ request.object.spec.storageClassName }}".
          RWX is not supported on Longhorn by default and requires explicit approval
          via annotation: storage.hypyr.space/rwx-approved="true"
        deny:
          conditions:
            all:
              # Block unless approval annotation is present
              - key: "{{ request.object.metadata.annotations.\"storage.hypyr.space/rwx-approved\" || 'false' }}"
                operator: NotEquals
                value: "true"

    # Rule 2: If RWX is approved, require justification annotation
    - name: require-rwx-justification
      match:
        any:
          - resources:
              kinds:
                - PersistentVolumeClaim
              annotations:
                storage.hypyr.space/rwx-approved: "true"
      preconditions:
        all:
          - key: "{{ request.object.spec.storageClassName }}"
            operator: AnyIn
            value:
              - longhorn
              - longhorn-static
              - longhorn-rwx
          - key: ReadWriteMany
            operator: AnyIn
            value: "{{ request.object.spec.accessModes }}"
      validate:
        message: >-
          PVC "{{ request.object.metadata.name }}" is approved for RWX but missing
          required justification annotation: storage.hypyr.space/rwx-justification
        pattern:
          metadata:
            annotations:
              storage.hypyr.space/rwx-approved: "true"
              storage.hypyr.space/rwx-justification: "?*"  # Must be non-empty
