---
version: "3"

vars:
  VOLSYNC_NAMESPACE: volsync-system

tasks:
  state-*:
    desc: Suspend or resume Volsync controller
    cmds:
      - flux --namespace {{.VOLSYNC_NAMESPACE}} {{.STATE}} helmrelease volsync
      - kubectl --namespace {{.VOLSYNC_NAMESPACE}} scale deployment volsync --replicas {{if eq .STATE "suspend"}}0{{else}}1{{end}}
    vars:
      STATE: "{{index .MATCH 0}}"
    preconditions:
      - '[[ "{{.STATE}}" == "suspend" || "{{.STATE}}" == "resume" ]]'
      - which flux kubectl

  unlock:
    desc: Unlock all restic source repos
    cmds:
      - for: { var: SOURCES, split: "\n" }
        cmd: kubectl --namespace {{splitList "," .ITEM | first}} patch --field-manager=flux-client-side-apply replicationsources {{splitList "," .ITEM | last}} --type merge --patch "{\"spec\":{\"restic\":{\"unlock\":\"{{now | unixEpoch}}\"}}}"
    vars:
      SOURCES:
        sh: kubectl get replicationsources --all-namespaces --no-headers --output=jsonpath='{range .items[*]}{.metadata.namespace},{.metadata.name}{"\n"}{end}'
    preconditions:
      - which kubectl

  snapshot:
    desc: Snapshot an app [NS={{.NS}}] [APP=required]
    cmds:
      - kubectl --namespace {{.NS}} patch replicationsources/{{.APP}} --type merge -p '{"spec":{"trigger":{"manual":"{{now | unixEpoch}}"}}}'
      - until kubectl --namespace {{.NS}} get job/{{.JOB}} >/dev/null 2>&1; do sleep 5; done
      - kubectl --namespace {{.NS}} wait job/{{.JOB}} --for=condition=complete --timeout=120m
    vars:
      NS: '{{.NS | default "default"}}'
      JOB: volsync-src-{{.APP}}
    requires:
      vars: [APP]
    preconditions:
      - kubectl --namespace {{.NS}} get replicationsources {{.APP}}
      - which kubectl

  fix-stuck-app:
    desc: Complete workflow to fix stuck VolSync apps with corrupted snapshots [APP=required] [NS={{.NS}}]
    requires:
      vars: [APP]
    vars:
      NS: '{{.NS | default "default"}}'
      POD_LABEL_SELECTOR: 'app.kubernetes.io/name={{.APP}}'
    preconditions:
      - which kubectl flux
    cmds:
      - task volsync:state-suspend
      - kubectl scale deployment {{.APP}} -n {{.NS}} --replicas=0
      - kubectl wait --for=delete pod -l {{.POD_LABEL_SELECTOR}} -n {{.NS}} --timeout=300s || true
      - kubectl delete volumesnapshot -l app.kubernetes.io/name={{.APP}} -n {{.NS}} --ignore-not-found --timeout=60s || true
      - |-
        kubectl get volumesnapshot -l app.kubernetes.io/name={{.APP}} -n {{.NS}} -o name 2>/dev/null | \
        xargs -r -I {} kubectl patch {} -n {{.NS}} -p '{"metadata":{"finalizers":null}}' --type=merge || true
      - |-
        kubectl get pvc -l app.kubernetes.io/name={{.APP}} -n {{.NS}} -o name 2>/dev/null | \
        xargs -r -I {} kubectl patch {} -n {{.NS}} -p '{"metadata":{"finalizers":null}}' --type=merge || true
      - kubectl delete pvc -l app.kubernetes.io/name={{.APP}} -n {{.NS}} --ignore-not-found --timeout=60s || true
      - task volsync:state-resume
      - kubectl wait --namespace {{.VOLSYNC_NAMESPACE}} --for=condition=Available deployment/volsync --timeout=120s || true
      - kubectl scale deployment {{.APP}} -n {{.NS}} --replicas=1
      - echo "Workflow complete! Monitor app with kubectl get pods -n {{.NS}}"
