#@ load("@ytt:data", "data")

#! ============================================================================
#! Talos Base Configuration Template (ytt Data Values)
#! ============================================================================
#!
#! Uses ytt data values pattern for variable substitution.
#! Node-specific values provided via: --data-values-file values/{node}.yaml
#!
#! See: ADR-0013 (ytt data values for Talos templating)
#!
#! Storage System: Longhorn
#! This configuration includes all requirements for Longhorn CSI:
#!   - NBD kernel module (block device replication)
#!   - iSCSI/iscsi_tcp (data path between replicas)
#!   - dm_multipath (path redundancy)
#!   - discard_unpacked_layers=false in Containerd (image layer caching)
#!
#! Change Control:
#!   - Modifications require ADR justification
#!   - Test on single node before cluster-wide rollout
#!
#! Danger Zones:
#!   - PKI references (op://...) must never be interpolated
#!   - Network subnets are immutable after cluster creation
#! ============================================================================

#! ----------------------------------------------------------------------------
#! Hardware-specific values lookup function
#! Returns hardware-type-specific configuration
#! ----------------------------------------------------------------------------
#@ def hardware_config():
#@   if data.values.hardware_type == "eq12":
#@     return {
#@       "factory_image": "factory.talos.dev/metal-installer/b12c79d1a286654d04583aa9fd9bde4324d1fd5bc694071397a62cb58deafb1c:v1.11.0-rc.0",
#@       "kubelet_cpu_reserved": "500m",
#@       "kubelet_memory_reserved": "2Gi",
#@       "hugepages": "1024",
#@       "swappiness": "10",
#@       "quicksync_gen": "12",
#@       "instance_type": "",
#@       "bond_selectors": [{"hardwareAddr": "7c:83:34:*", "driver": "igc"}],
#@       "bond_interfaces": [],
#@       "vlans": [{"vlanId": 10, "dhcp": False, "mtu": 1500}, {"vlanId": 48, "dhcp": False, "mtu": 1500}],
#@       "ethernet_configs": [{"name": "enp1s0"}, {"name": "enp2s0"}],
#@       "extra_sysctls": {},
#@     }
#@   elif data.values.hardware_type == "p520":
#@     return {
#@       "factory_image": "factory.talos.dev/metal-installer/d38be64a0b19b7e98c10e4374e55ea1720b4edea1b95d45c3dc170986ad33082:v1.11.0-rc.0",
#@       "kubelet_cpu_reserved": "2000m",
#@       "kubelet_memory_reserved": "8Gi",
#@       "hugepages": "8192",
#@       "swappiness": "1",
#@       "quicksync_gen": "",
#@       "instance_type": "p520-xeon",
#@       "bond_selectors": [],
#@       "bond_interfaces": ["enp23s0f1np1", "enp23s0f0np0"],
#@       "vlans": [{"vlanId": 10, "dhcp": False, "mtu": 1500}, {"vlanId": 48, "dhcp": False, "mtu": 1500}],
#@       "ethernet_configs": [],
#@       "extra_sysctls": {
#@         "vm.max_map_count": "2097152",
#@         "kernel.pid_max": "262144",
#@       },
#@     }
#@   elif data.values.hardware_type == "itx":
#@     return {
#@       "factory_image": "factory.talos.dev/metal-installer/b12c79d1a286654d04583aa9fd9bde4324d1fd5bc694071397a62cb58deafb1c:v1.11.0-rc.0",
#@       "kubelet_cpu_reserved": "1000m",
#@       "kubelet_memory_reserved": "4Gi",
#@       "hugepages": "4096",
#@       "swappiness": "10",
#@       "quicksync_gen": "7",
#@       "instance_type": "itx",
#@       "bond_selectors": [{"driver": "e1000e", "pciID": "8086:15bc"}, {"driver": "igb", "pciID": "8086:1539"}],
#@       "bond_interfaces": [],
#@       "vlans": [{"vlanId": 10, "dhcp": False, "mtu": 1500}, {"vlanId": 48, "dhcp": False, "mtu": 1500}],
#@       "ethernet_configs": [],
#@       "extra_sysctls": {
#@         "vm.max_map_count": "1048576",
#@       },
#@     }
#@   end
#@ end

#@ hw = hardware_config()

---
version: v1alpha1
debug: false
persist: true

machine:
  type: controlplane
  
  #! Machine PKI - 1Password References (MUST NOT be interpolated)
  token: op://homelab/talos/MACHINE_TOKEN
  ca:
    crt: op://homelab/talos/MACHINE_CA_CRT
    key: op://homelab/talos/MACHINE_CA_KEY
  
  #! Certificate SANs - all cluster members
  certSANs:
    - homeops.hypyr.space
    - home01.hypyr.space
    - home02.hypyr.space
    - home04.hypyr.space
    - home05.hypyr.space
    - home01
    - home02
    - home04
    - home05
  
  features:
    rbac: true
    stableHostname: true
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:admin
      allowedKubernetesNamespaces:
        - actions-runner-system
        - system-upgrade
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      resolveMemberNames: true
      forwardKubeDNSToHost: false
  
  files:
    - op: create
      path: /etc/cri/conf.d/20-customization.part
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          device_ownership_from_security_context = true
    - op: overwrite
      path: /etc/nfsmount.conf
      permissions: 420
      content: |
        [ NFSMount_Global_Options ]
        nfsvers=4.1
        hard=True
        nconnect=8
        noatime=True
        rsize=1048576
        wsize=1048576
  
  install:
    image: #@ hw["factory_image"]
    disk: #@ data.values.install_disk
  
  kernel:
    modules:
      - name: nbd
      - name: iscsi_tcp
      - name: dm_multipath
  
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.34.2
    extraConfig:
      featureGates:
        KubeletSeparateDiskGC: true
      evictionHard:
        imagefs.available: "5%"
        nodefs.available: "5%"
      evictionMinimumReclaim:
        imagefs.available: "10%"
        nodefs.available: "10%"
      systemReserved:
        cpu: #@ hw["kubelet_cpu_reserved"]
        memory: #@ hw["kubelet_memory_reserved"]
      kubeReserved:
        cpu: #@ hw["kubelet_cpu_reserved"]
        memory: #@ hw["kubelet_memory_reserved"]
    defaultRuntimeSeccompProfileEnabled: true
    nodeIP:
      validSubnets:
        - 10.0.5.0/24
    disableManifestsDirectory: true
  
  network:
    hostname: #@ data.values.hostname
    nameservers:
      - 10.0.5.1
    disableSearchDomain: true
    interfaces:
      - interface: bond0
        bond:
          #@ if len(hw["bond_selectors"]) > 0:
          deviceSelectors: #@ hw["bond_selectors"]
          #@ end
          #@ if len(hw["bond_interfaces"]) > 0:
          interfaces: #@ hw["bond_interfaces"]
          #@ end
          mode: 802.3ad
          xmitHashPolicy: layer3+4
          lacpRate: fast
          miimon: 1000
        addresses:
          - #@ data.values.ip_address
        routes:
          - network: 0.0.0.0/0
            gateway: #@ data.values.gateway
        mtu: 1500
        #@ if len(hw["vlans"]) > 0:
        vlans: #@ hw["vlans"]
        #@ end
  
  nodeLabels:
    topology.kubernetes.io/region: #@ data.values.topology_region
    topology.kubernetes.io/zone: #@ data.values.topology_zone
    postgres.priority: #@ data.values.postgres_priority
    #@ if hw["quicksync_gen"] != "":
    quicksync.generation: #@ hw["quicksync_gen"]
    #@ end
    #@ if hw["instance_type"] != "":
    node.kubernetes.io/instance-type: #@ hw["instance_type"]
    #@ end
  
  sysctls:
    fs.inotify.max_user_watches: "1048576"
    fs.inotify.max_user_instances: "8192"
    net.core.rmem_max: "67108864"
    net.core.wmem_max: "67108864"
    net.ipv4.tcp_congestion_control: bbr
    net.ipv4.tcp_fastopen: "3"
    sunrpc.tcp_slot_table_entries: "128"
    sunrpc.tcp_max_slot_table_entries: "128"
    user.max_user_namespaces: "11255"
    vm.nr_hugepages: #@ hw["hugepages"]
    vm.swappiness: #@ hw["swappiness"]
    #@ if data.values.hardware_type == "p520":
    vm.max_map_count: "2097152"
    kernel.pid_max: "262144"
    #@ elif data.values.hardware_type == "itx":
    vm.max_map_count: "1048576"
    #@ end
  
  time:
    disabled: false
    servers:
      - time.cloudflare.com

cluster:
  ca:
    crt: op://homelab/talos/CLUSTER_CA_CRT
    key: op://homelab/talos/CLUSTER_CA_KEY
  clusterName: homeops
  controlPlane:
    endpoint: https://homeops.hypyr.space:6443
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service:
        disabled: false
  id: op://homelab/talos/CLUSTER_ID
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  secret: op://homelab/talos/CLUSTER_SECRET
  token: op://homelab/talos/CLUSTER_TOKEN
  aggregatorCA:
    crt: op://homelab/talos/CLUSTER_AGGREGATORCA_CRT
    key: op://homelab/talos/CLUSTER_AGGREGATORCA_KEY
  allowSchedulingOnControlPlanes: true
  
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.34.2
    extraArgs:
      enable-aggregator-routing: "true"
      bind-address: 0.0.0.0
    certSANs:
      - homeops.hypyr.space
    disablePodSecurityPolicy: true
  
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.34.2
    extraArgs:
      bind-address: 0.0.0.0
  
  coreDNS:
    disabled: true
  
  etcd:
    advertisedSubnets:
      - 10.0.5.0/24
    ca:
      crt: op://homelab/talos/CLUSTER_ETCD_CA_CRT
      key: op://homelab/talos/CLUSTER_ETCD_CA_KEY
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
  
  extraManifests:
    #! renovate: datasource=github-releases depName=kubernetes-sigs/gateway-api
    - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml
    #! renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
    - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.87.0/stripped-down-crds.yaml
  
  proxy:
    disabled: true
    image: registry.k8s.io/kube-proxy:v1.34.2
  
  secretboxEncryptionSecret: op://homelab/talos/CLUSTER_SECRETBOXENCRYPTIONSECRET
  
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.34.2
    extraArgs:
      bind-address: 0.0.0.0
    config:
      apiVersion: kubescheduler.config.k8s.io/v1
      kind: KubeSchedulerConfiguration
      profiles:
        - schedulerName: default-scheduler
          plugins:
            score:
              disabled:
                - name: ImageLocality
          pluginConfig:
            - name: PodTopologySpread
              args:
                defaultingType: List
                defaultConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
  
  serviceAccount:
    key: op://homelab/talos/CLUSTER_SERVICEACCOUNT_KEY

---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk && disk.transport == "sata"
  maxSize: 100GiB

---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-storage
provisioning:
  diskSelector:
    match: system_disk && disk.transport == "sata"
  minSize: 100GiB

#@ for eth in hw["ethernet_configs"]:
---
apiVersion: v1alpha1
kind: EthernetConfig
name: #@ eth["name"]
rings:
  rx: 4096
  tx: 4096
#@ end
