name: "Propose a Policy Change"
description: "Change constitution/contracts/requirements (normative governance). ADR REQUIRED."
title: "policy: <short description> (ADR-NNNN)"
labels: ["contracts", "needs-adr"]
body:
  - type: markdown
    attributes:
      value: |
        ## Policy Change Template
        
        This template is for **normative governance changes** (constitution/contracts/requirements).
        If you're changing implementation only, use a Feature Request or Agent Task.
        
        **⚠️ CRITICAL:** Canonical changes require `ADR-NNNN` pattern in PR title/body.
        The CI gate `require_adr_for_canonical_changes` will block PRs without this reference.

  - type: dropdown
    id: authority
    attributes:
      label: Authority level impacted
      options:
        - constitution/
        - contracts/
        - requirements/
      description: "Which authoritative layer will change?"
    validations:
      required: true

  - type: input
    id: adr
    attributes:
      label: ADR reference (REQUIRED)
      description: "Provide the ADR ID (e.g., ADR-0032). This MUST appear in the PR title or body for gates to pass."
      placeholder: "ADR-0032"
    validations:
      required: true

  - type: textarea
    id: invariant
    attributes:
      label: Invariant touched
      description: "If this changes an invariant, paste the exact bullet/section from contracts/invariants.md. If none, say 'None'."
      placeholder: |
        e.g. contracts/invariants.md -> Access Invariants -> "Management network has no Internet egress by default"
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: Proposed change
      description: "What exactly is changing? Use MUST/MUST NOT wording where relevant."
      placeholder: |
        - Change: ...
        - Reason: ...
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Document status
      description: "Select status for governance documents. Proposed requires explicit human approval before commit."
      options:
        - Proposed (requires approval; cannot be committed)
        - Accepted (approved)
    validations:
      required: true

  - type: textarea
    id: rollback
    attributes:
      label: Rollback plan (required)
      description: "How do we revert safely if this causes issues? Include timebox if it's an exception."
      placeholder: |
        - Timebox: (e.g., 30 minutes / until firmware update completes)
        - Rollback steps: ...
        - Verification: ...
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / mitigations
      description: "Any new risks? If yes, add/update docs/risk/risk-register.md."
      placeholder: |
        - Risk: ...
        - Mitigation: ...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission checklist
      options:
        - label: "I understand the PR title/body MUST include ADR-NNNN pattern for gates to pass"
          required: true
        - label: "I will link the ADR from the relevant requirements/**/spec.md"
          required: true
        - label: "I will not commit governance documents with `Status: Proposed` (approval required)"
          required: true
        - label: "If this is break-glass, I will timebox it and document restoration"
          required: false
