apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-external-secrets-operator
  annotations:
    policies.kyverno.io/title: Require External Secrets Operator
    policies.kyverno.io/category: Secrets
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ExternalSecret
    policies.kyverno.io/description: >-
      Blocks ExternalSecret resources if the External Secrets Operator deployment
      is not present. Prevents users from applying ExternalSecrets before ESO is
      installed during bootstrap.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: eso-must-exist
      match:
        any:
          - resources:
              kinds:
                - ExternalSecret
      context:
        - name: esoDeployments
          apiCall:
            url: "https://kubernetes.default.svc/apis/apps/v1/namespaces/external-secrets/deployments?fieldSelector=metadata.name=external-secrets"
            jmesPath: "items[].metadata.name"
      validate:
        message: >-
          External Secrets Operator is not present (Deployment external-secrets in namespace external-secrets).
          Install ESO before applying ExternalSecret resources.
        deny:
          conditions:
            any:
              - key: "{{ len(esoDeployments) }}"
                operator: Equals
                value: 0
