apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-allowed-secret-store
  annotations:
    policies.kyverno.io/title: Require Allowed External Secret Stores
    policies.kyverno.io/category: Secrets
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: ExternalSecret
    policies.kyverno.io/description: >-
      Ensures ExternalSecret resources reference only approved secret stores.
      Prevents accidents where an ExternalSecret points to a non-existent or
      unintended SecretStore/ClusterSecretStore (common bootstrap footgun).
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-approved-store
      match:
        any:
          - resources:
              kinds:
                - ExternalSecret
      validate:
        message: >-
          ExternalSecret {{ request.object.metadata.name }} must reference an approved store
          (ClusterSecretStore: onepassword). Set spec.secretStoreRef.kind=ClusterSecretStore
          and name to one of the allowed stores.
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.secretStoreRef.kind || '' }}"
                operator: NotEquals
                value: ClusterSecretStore
              - key: "{{ request.object.spec.secretStoreRef.name || '' }}"
                operator: AnyNotIn
                value:
                  - onepassword
