services:
  caddy:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
      labels:
        # Homepage dashboard
        homepage.group: "Infrastructure"
        homepage.name: "Caddy"
        homepage.icon: "caddy.png"
        homepage.href: "https://barbary.in.hypyr.space"
        homepage.description: "Reverse proxy & TLS"

        # Caddy self-configuration
        caddy.email: admin@hypyr.space
        caddy_10: barbary.in.hypyr.space
        caddy_10.reverse_proxy: host.docker.internal:81
        caddy_10.tls.dns: "cloudflare {env.CLOUDFLARE_API_TOKEN}"
        caddy_90: '*.in.hypyr.space'
        caddy_90.respond: not-found 404
        caddy_90.tls.dns: "cloudflare {env.CLOUDFLARE_API_TOKEN}"

        # AutoKuma monitoring (via proxied service to test Caddy is working)
        kuma.caddy.http.name: "Caddy Reverse Proxy"
        kuma.caddy.http.url: "https://home.in.hypyr.space"
        kuma.caddy.http.interval: "60"
        kuma.caddy.http.maxretries: "3"
        kuma.caddy.http.accepted_statuscodes: '["200-299","302"]'

    entrypoint: ["/bin/sh", "-c"]
    command: >
      "export CLOUDFLARE_API_TOKEN=$$(cat /run/secrets/CLOUDFLARE_API_TOKEN) &&
       exec caddy docker-proxy"
    environment:
      CADDY_INGRESS_NETWORKS: proxy_network
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      TZ: America/Chicago
      CADDY_EMAIL: admin@hypyr.space
    secrets:
      - CLOUDFLARE_API_TOKEN
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/cpritchett/caddy-labels:latest
    networks:
      - proxy_network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    user: '1701:1702'
    volumes:
      - /mnt/apps01/appdata/proxy/caddy-data:/data/caddy
      - /mnt/apps01/appdata/proxy/caddy-config:/config

  cloudflared-secrets:
    image: 1password/op:2@sha256:57d7d6a2bb2b74b2cf8111f6afb2973c74772198f82ea30359a53faae9fff5b1
    deploy:
      mode: replicated-job
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      OP_CONNECT_HOST: http://op-connect-api:8080
      OP_CONNECT_TOKEN_FILE: /run/secrets/op_connect_token
    secrets:
      - op_connect_token
    volumes:
      - ./cloudflared-env.template:/templates/cloudflared.template:ro
      - ./cloudflared-config.yaml:/templates/cloudflared-config.template:ro
      - /mnt/apps01/appdata/cloudflared/secrets:/secrets
    networks:
      - op-connect
    command: >
      sh -ec "
      export OP_CONNECT_TOKEN=$$(cat /run/secrets/op_connect_token) &&
      op inject -i /templates/cloudflared.template -o /secrets/cloudflared.env -f &&
      op inject -i /templates/cloudflared-config.template -o /secrets/config.yaml -f &&
      . /secrets/cloudflared.env &&
      echo \"$${CREDENTIALS_JSON}\" | base64 -d > /secrets/credentials.json &&
      chmod 644 /secrets/cloudflared.env /secrets/credentials.json /secrets/config.yaml &&
      echo 'Cloudflared secrets injected successfully'
      "

  cloudflared:
    image: cloudflare/cloudflared:2026.2.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        homepage.group: "Infrastructure"
        homepage.name: "Cloudflare Tunnel"
        homepage.icon: "cloudflare.png"
        homepage.href: "https://dash.cloudflare.com"
        homepage.description: "External ingress tunnel"

        kuma.cloudflared.http.name: "Cloudflare Tunnel"
        kuma.cloudflared.http.url: "http://cloudflared:2000/ready"
        kuma.cloudflared.http.interval: "60"
        kuma.cloudflared.http.maxretries: "3"
        kuma.cloudflared.http.accepted_statuscodes: '["200-299"]'
    command: ["tunnel", "--config", "/secrets/config.yaml", "run"]
    volumes:
      - /mnt/apps01/appdata/cloudflared/secrets:/secrets:ro
    networks:
      - proxy_network
    user: '65532:999'

  docker-socket-proxy:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      CONFIGS: '1'
      CONTAINERS: '1'
      EVENTS: '1'
      INFO: '1'
      NETWORKS: '1'
      NODES: '1'
      PING: '1'
      SERVICES: '1'
      SWARM: '1'
      TASKS: '1'
      TIMEOUT_CLIENT: 300s
      TIMEOUT_CONNECT: 30s
      TIMEOUT_SERVER: 300s
      VERSION: '1'
    healthcheck:
      interval: 10s
      retries: 10
      test:
        - CMD
        - wget
        - '-qO-'
        - http://localhost:2375/_ping
      timeout: 3s
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    networks:
      - proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy_network:
    external: true
  op-connect:
    name: op-connect_op-connect
    external: true

secrets:
  CLOUDFLARE_API_TOKEN:
    external: true
  op_connect_token:
    external: true
