services:
  caddy:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
      labels:
        # Homepage dashboard
        homepage.group: "Infrastructure"
        homepage.name: "Caddy"
        homepage.icon: "caddy.png"
        homepage.href: "https://barbary.in.hypyr.space"
        homepage.description: "Reverse proxy & TLS"

        # Caddy self-configuration
        caddy.email: admin@hypyr.space
        caddy_10: barbary.in.hypyr.space
        caddy_10.reverse_proxy: host.docker.internal:81
        caddy_10.tls.dns: "cloudflare {env.CLOUDFLARE_API_TOKEN}"
        caddy_90: '*.in.hypyr.space'
        caddy_90.respond: not-found 404
        caddy_90.tls.dns: "cloudflare {env.CLOUDFLARE_API_TOKEN}"

        # AutoKuma monitoring (via proxied service to test Caddy is working)
        kuma.caddy.http.name: "Caddy Reverse Proxy"
        kuma.caddy.http.url: "https://home.in.hypyr.space"
        kuma.caddy.http.interval: "60"
        kuma.caddy.http.maxretries: "3"

    entrypoint: ["/bin/sh", "-c"]
    command: >
      "export CLOUDFLARE_API_TOKEN=$$(cat /run/secrets/CLOUDFLARE_API_TOKEN) &&
       exec caddy docker-proxy"
    environment:
      CADDY_INGRESS_NETWORKS: proxy_network
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      TZ: America/Chicago
      CADDY_EMAIL: admin@hypyr.space
    secrets:
      - CLOUDFLARE_API_TOKEN
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/cpritchett/caddy-labels:latest
    networks:
      - proxy_network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    user: '1701:1702'
    volumes:
      - /mnt/apps01/appdata/proxy/caddy-data:/data/caddy
      - /mnt/apps01/appdata/proxy/caddy-config:/config

  docker-socket-proxy:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      CONTAINERS: '1'
      EVENTS: '1'
      INFO: '1'
      NETWORKS: '1'
      NODES: '1'
      PING: '1'
      SERVICES: '1'
      SWARM: '1'
      TASKS: '1'
      TIMEOUT_CLIENT: 300s
      TIMEOUT_CONNECT: 30s
      TIMEOUT_SERVER: 300s
      VERSION: '1'
    healthcheck:
      interval: 10s
      retries: 10
      test:
        - CMD
        - wget
        - '-qO-'
        - http://localhost:2375/_ping
      timeout: 3s
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    networks:
      - proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy_network:
    external: true

secrets:
  CLOUDFLARE_API_TOKEN:
    external: true
