services:
  core:
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_DB_NAME: komodo
      KOMODO_DATABASE_USERNAME: admin
      KOMODO_DATABASE_PASSWORD_FILE: /run/secrets/komodo_db_password
      KOMODO_DISABLE_USER_REGISTRATION: "false"
      KOMODO_ENABLE_NEW_USERS: "true"
      KOMODO_FIRST_SERVER: https://periphery:8120
      KOMODO_HOST: https://komodo.in.hypyr.space
      KOMODO_LOCAL_AUTH: "true"
      KOMODO_PASSKEY_FILE: /run/secrets/komodo_passkey
      KOMODO_PORT: "30160"
      KOMODO_SYNC_DIRECTORY: /syncs
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
      UMASK: '002'
      UMASK_SET: '002'
    healthcheck:
      interval: 30s
      retries: 10
      start_period: 120s
      test:
        - CMD-SHELL
        - curl -sS -o /dev/null http://127.0.0.1:30160/ || exit 1
      timeout: 5s
    image: ghcr.io/moghtech/komodo-core:2-dev
    labels:
      caddy_0.tls: internal
      caddy_0: komodo.in.hypyr.space
      caddy_0.reverse_proxy: core:30160
    networks:
      - proxy_network
      - default
    privileged: false
    security_opt:
      - no-new-privileges=true
    stdin_open: false
    tty: false
    volumes:
      - /mnt/apps01/appdata/komodo/backups:/backups
      - /mnt/apps01/appdata/komodo/sync:/syncs
    secrets:
      - komodo_db_password
      - komodo_passkey

  mongo:
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    environment:
      MONGO_INITDB_DATABASE: komodo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/komodo_db_password
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
      UMASK: '002'
      UMASK_SET: '002'
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test:
        - CMD
        - mongosh
        - '--host'
        - 127.0.0.1
        - '--port'
        - '27017'
        - komodo
        - '--eval'
        - db.adminCommand("ping")
        - '--quiet'
      timeout: 5s
    image: mongo:8.2.3
    labels:
      komodo.skip: 'true'
    privileged: false
    security_opt:
      - no-new-privileges=true
    stdin_open: false
    stop_grace_period: 60s
    tty: false
    user: '568:568'
    volumes:
      - /mnt/apps01/appdata/komodo/mongodb:/data/db
    secrets:
      - komodo_db_password

  periphery:
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    environment:
      PERIPHERY_PASSKEYS_FILE: /run/secrets/komodo_passkey
      PERIPHERY_PORT: "8120"
      PERIPHERY_ROOT_DIRECTORY: /mnt/apps01/repos
      PERIPHERY_SSL_ENABLED: "true"
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
      UMASK: '002'
      UMASK_SET: '002'
    healthcheck:
      disable: true
    image: ghcr.io/moghtech/komodo-periphery:2-dev
    labels:
      komodo.skip: 'true'
    networks:
      - proxy_network
      - default
    privileged: false
    security_opt:
      - no-new-privileges=true
    stdin_open: false
    tty: false
    volumes:
      - /mnt/apps01/repos:/mnt/apps01/repos
      - /proc:/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - komodo_passkey

networks:
  proxy_network:
    external: true
  op-connect:
    external:
      name: op-connect_op-connect
  default:
    driver: overlay

secrets:
  komodo_db_password:
    external: true
  komodo_passkey:
    external: true
