services:
  core:
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "set -a &&
       [ -f /secrets/komodo.env ] && . /secrets/komodo.env || true &&
       set +a &&
       exec /app/core"
    environment:
      KOMODO_SYNC_DIRECTORY: /syncs
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
      UMASK: '002'
      UMASK_SET: '002'
    healthcheck:
      interval: 30s
      retries: 10
      start_period: 120s
      test:
        - CMD-SHELL
        - curl -sS -o /dev/null http://127.0.0.1:30160/ || exit 1
      timeout: 5s
    image: ghcr.io/moghtech/komodo-core:2-dev
    labels:
      caddy_0.tls: internal
      caddy_0: komodo.in.hypyr.space
      caddy_0.reverse_proxy: core:30160
    networks:
      - proxy_network
      - default
      - op-connect
    privileged: false
    security_opt:
      - no-new-privileges=true
    stdin_open: false
    tty: false
    volumes:
      - /mnt/apps01/appdata/komodo/backups:/backups
      - /mnt/apps01/appdata/komodo/sync:/syncs
      - /mnt/apps01/repos/homelab/stacks/platform/komodo/komodo.template:/templates/komodo.template:ro
      - /mnt/apps01/appdata/komodo/secrets:/secrets
    secrets:
      - op_connect_token

  mongo:
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "set -a &&
       op inject -i /templates/komodo.template -o /secrets/komodo.env -f 2>/dev/null || true &&
       [ -f /secrets/komodo.env ] && . /secrets/komodo.env || true &&
       set +a &&
       exec docker-entrypoint.sh mongod"
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
      UMASK: '002'
      UMASK_SET: '002'
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test:
        - CMD
        - mongosh
        - '--host'
        - 127.0.0.1
        - '--port'
        - '27017'
        - komodo
        - '--eval'
        - db.adminCommand("ping")
        - '--quiet'
      timeout: 5s
    image: mongo:8.2.3
    labels:
      komodo.skip: 'true'
    privileged: false
    security_opt:
      - no-new-privileges=true
    stdin_open: false
    stop_grace_period: 60s
    tty: false
    user: '568:568'
    volumes:
      - /mnt/apps01/appdata/komodo/mongodb:/data/db
      - /mnt/apps01/appdata/komodo/secrets:/secrets
      - /mnt/apps01/repos/homelab/stacks/platform/komodo/komodo.template:/templates/komodo.template:ro
    secrets:
      - op_connect_token

  periphery:
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "set -a &&
       op inject -i /templates/komodo.template -o /secrets/komodo.env -f 2>/dev/null || true &&
       [ -f /secrets/komodo.env ] && . /secrets/komodo.env || true &&
       set +a &&
       exec /app/periphery"
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      PERIPHERY_PORT: 8120
      PERIPHERY_ROOT_DIRECTORY: /mnt/apps01/repos
      PERIPHERY_SSL_ENABLED: 'true'
      TZ: America/Chicago
      UMASK: '002'
      UMASK_SET: '002'
    healthcheck:
      disable: true
    image: ghcr.io/moghtech/komodo-periphery:2-dev
    labels:
      komodo.skip: 'true'
    networks:
      - proxy_network
      - default
      - op-connect
    privileged: false
    security_opt:
      - no-new-privileges=true
    stdin_open: false
    tty: false
    volumes:
      - /mnt/apps01/repos:/mnt/apps01/repos
      - /proc:/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/apps01/appdata/komodo/secrets:/secrets
      - /mnt/apps01/repos/homelab/stacks/platform/komodo/komodo.template:/templates/komodo.template:ro
    secrets:
      - op_connect_token

networks:
  proxy_network:
    external: true
  op-connect:
    external:
      name: op-connect_op-connect
  default:
    driver: overlay

secrets:
  op_connect_token:
    external: true
