services:
  op-connect-api:
    image: 1password/connect-api:1.7.3
    hostname: op-connect-api
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
      placement:
        constraints:
          - node.hostname == barbary
      labels:
        # Homepage dashboard
        homepage.group: "Infrastructure"
        homepage.name: "1Password Connect"
        homepage.icon: "1password.png"
        homepage.href: "http://op-connect-api:8080"
        homepage.description: "Secrets management"
        homepage.widget.type: "customapi"
        homepage.widget.url: "http://op-connect-api:8080/health"
        homepage.widget.mappings.0.field: "name"
        homepage.widget.mappings.0.label: "Service"
        homepage.widget.mappings.1.field: "version"
        homepage.widget.mappings.1.label: "Version"

        # Caddy reverse proxy (optional - usually internal only)
        caddy: op-connect.in.hypyr.space
        caddy.reverse_proxy: "op-connect-api:8080"
        caddy.tls.dns: "cloudflare {env.CLOUDFLARE_API_TOKEN}"

        # AutoKuma monitoring (internal health check)
        kuma.op-connect.http.name: "1Password Connect API"
        kuma.op-connect.http.url: "http://op-connect-api:8080/health"
        kuma.op-connect.http.interval: "60"
        kuma.op-connect.http.maxretries: "5"
        # Deep readiness checks (detect upstream/activeKeyset failures)
        kuma.op-connect-readiness.keyword.name: "1Password Connect Readiness"
        kuma.op-connect-readiness.keyword.url: "http://op-connect-api:8080/health"
        kuma.op-connect-readiness.keyword.keyword: "ACTIVE"
        kuma.op-connect-readiness.keyword.interval: "60"
        kuma.op-connect-sync.keyword.name: "1Password Connect Sync"
        kuma.op-connect-sync.keyword.url: "http://op-connect-api:8080/health"
        kuma.op-connect-sync.keyword.keyword: "ACTIVE"
        kuma.op-connect-sync.keyword.interval: "60"

    volumes:
      - op-connect-data:/home/opuser/.op/data
      - /mnt/apps01/secrets/op/1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro
    environment:
      OP_SESSION: /home/opuser/.op/1password-credentials.json
      OP_LOG_LEVEL: ${OP_LOG_LEVEL:-info}
    secrets:
      - CLOUDFLARE_API_TOKEN
    networks:
      op-connect:
        aliases:
          - op-connect-api
      proxy_network:
    healthcheck:
      disable: true

  op-connect-sync:
    image: 1password/connect-sync:1.7.3
    hostname: op-connect-sync
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
      placement:
        constraints:
          - node.hostname == barbary
    volumes:
      - op-connect-data:/home/opuser/.op/data
      - /mnt/apps01/secrets/op/1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro
    environment:
      OP_SESSION: /home/opuser/.op/1password-credentials.json
      OP_LOG_LEVEL: ${OP_LOG_LEVEL:-info}
    networks:
      op-connect:
        aliases:
          - op-connect-sync
    healthcheck:
      disable: true

networks:
  op-connect:
    driver: overlay
    attachable: true
  proxy_network:
    external: true

volumes:
  op-connect-data:
    driver: local

secrets:
  CLOUDFLARE_API_TOKEN:
    external: true
