services:
  step-ca:
    image: smallstep/step-ca:latest
    deploy:
      placement:
        constraints:
          - node.hostname == barbary
      resources:
        limits:
          cpus: '1'
          memory: 512M
      labels:
        # AutoKuma monitoring
        kuma.step-ca.http.name: "Smallstep CA"
        kuma.step-ca.http.url: "https://step-ca:9000/health"
        kuma.step-ca.http.accepted_statuscodes: "200"
        kuma.step-ca.http.interval: "60"
        kuma.step-ca.http.maxretries: "3"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "if [ ! -f /home/step/config/ca.json ]; then
         echo 'First boot: initializing Smallstep CA...' &&
         step ca init --name 'Homelab CA' --dns 'step-ca,localhost' --address ':9000' --provisioner admin --password-file /run/secrets/step_ca_password --provisioner-password-file /run/secrets/step_ca_password &&
         sed -i 's|\"provisioners\"|\"claims\": {\"maxTLSCertDuration\": \"8760h\", \"defaultTLSCertDuration\": \"720h\"},\n\t\t\"provisioners\"|' /home/step/config/ca.json &&
         echo 'CA initialized with 1-year max cert duration';
       fi &&
       exec step-ca --password-file /run/secrets/step_ca_password /home/step/config/ca.json"
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
    healthcheck:
      test:
        - CMD
        - step
        - ca
        - health
        - --ca-url
        - https://localhost:9000
        - --root
        - /home/step/certs/root_ca.crt
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - proxy_network
      - default
    volumes:
      - /mnt/apps01/appdata/step-ca:/home/step
    secrets:
      - step_ca_password

  cert-init:
    image: smallstep/step-cli:latest
    deploy:
      mode: replicated-job
      placement:
        constraints:
          - node.hostname == barbary
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "CA=/step-ca-data &&
       ISSUED=$$CA/issued/periphery &&
       ROOT=$$CA/certs/root_ca.crt &&
       URL=https://step-ca:9000 &&
       TRIES=0 &&
       echo 'Waiting for step-ca...' &&
       while [ $$TRIES -lt 60 ]; do
         step ca health --ca-url $$URL --root $$ROOT 2>/dev/null && break;
         TRIES=$$((TRIES + 1));
         echo \"Attempt $$TRIES/60 - waiting 5s...\";
         sleep 5;
       done &&
       if [ $$TRIES -eq 60 ]; then echo 'ERROR: step-ca timeout'; exit 1; fi &&
       mkdir -p $$ISSUED &&
       step ca certificate periphery $$ISSUED/cert.pem $$ISSUED/key.pem --san periphery --san localhost --san barbary --san barbary.in.hypyr.space --not-after 8760h --ca-url $$URL --root $$ROOT --provisioner admin --provisioner-password-file /run/secrets/step_ca_password --force &&
       chmod 644 $$ISSUED/cert.pem &&
       chmod 600 $$ISSUED/key.pem &&
       cp $$ROOT $$CA/issued/root_ca.crt &&
       chmod 644 $$CA/issued/root_ca.crt &&
       echo 'Certificate issued:' &&
       step certificate inspect $$ISSUED/cert.pem --short"
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
    networks:
      - default
    volumes:
      - /mnt/apps01/appdata/step-ca:/step-ca-data
    secrets:
      - step_ca_password

networks:
  proxy_network:
    external: true
  default:
    driver: overlay

secrets:
  step_ca_password:
    external: true
