# Secret Hydration Contract: One-Shot Job Pattern
# All Docker Swarm stacks requiring secrets MUST use this pattern (ADR-0035)

---
apiVersion: v1
kind: SecretHydrationContract
metadata:
  name: one-shot-secret-hydration
  spec: "002-label-driven-swarm-infrastructure"
  adr: ADR-0035

# Job Service Definition
job:
  deploy:
    mode: replicated-job
    restart_policy:
      condition: none
    resources:
      limits:
        cpus: "0.5"
        memory: "256M"

  image:
    repository: 1password/op
    tag: "2"
    digest: required  # Must include @sha256: pin

  environment:
    required:
      - name: OP_CONNECT_HOST
        value: "http://op-connect-api:8080"
      - name: OP_CONNECT_TOKEN_FILE
        value: "/run/secrets/op_connect_token"

  secrets:
    required:
      - name: op_connect_token
        external: true

  networks:
    required:
      - name: op-connect_op-connect
        alias: op-connect
        external: true

  command_pattern: |
    sh -ec "
    export OP_CONNECT_TOKEN=$$(cat /run/secrets/op_connect_token) &&
    op inject -i /templates/{template} -o /secrets/{output} -f &&
    chmod {permissions} /secrets/{output} &&
    echo 'Secrets injected successfully'
    "

# Template Format
template:
  format: "op://{vault}/{item}/{field}"
  vault: homelab
  mount: read-only
  path_pattern: "./env.template:/templates/{name}.template:ro"

# Output
output:
  path_pattern: "/mnt/apps01/appdata/{stack}/secrets"
  permissions: "644"
  ownership: varies  # Depends on consuming service UID

# Consumer Service Pattern
consumer:
  entrypoint: ["/bin/sh", "-c"]
  command_pattern: |
    "set -a && [ -f /secrets/{env_file} ] && . /secrets/{env_file} && set +a &&
     exec {original_command}"
  volume_mount: "/mnt/apps01/appdata/{stack}/secrets:/secrets:ro"

# Validation
validation:
  - rule: Job MUST show "0/1 (1/1 completed)" after success
    check: "docker service ls --filter name={stack}_op-secrets"

  - rule: Template files MUST NOT contain resolved secrets
    check: "grep -v 'op://' {template_file} should return empty"

  - rule: Output directory MUST have correct ownership
    check: "stat -c '%u:%g' /mnt/apps01/appdata/{stack}/secrets"

  - rule: Consuming service MUST NOT start if secrets file missing
    check: "[ -f /secrets/{env_file} ] test in entrypoint"
