apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-nodeport-services
  annotations:
    policies.kyverno.io/title: Deny NodePort Services (External Access)
    policies.kyverno.io/category: Ingress
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      Prevents Services of type NodePort that could be exposed to WAN.
      NodePort on cluster nodes with WAN reachability bypasses Cloudflare Tunnel.
      Internal NodePort for specific use cases (e.g., monitoring) may be allowed
      with explicit approval.
    hypyr.space/rationale: "https://github.com/cpritchett/homelab/blob/main/docs/adr/ADR-0002-tunnel-only-ingress.md"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    # Rule 1: Deny NodePort unless explicitly approved for internal use
    - name: deny-nodeport-without-approval
      match:
        any:
          - resources:
              kinds:
                - Service
      preconditions:
        all:
          # Only trigger if type is NodePort
          - key: "{{ request.object.spec.type }}"
            operator: Equals
            value: NodePort
      validate:
        message: >-
          Service "{{ request.object.metadata.name }}" with type NodePort is
          prohibited unless explicitly approved for internal use. NodePort can
          expose services to WAN if firewall rules are misconfigured. Use
          ClusterIP with Ingress/Gateway API for external access via Cloudflare Tunnel.
          For approved internal NodePort, add annotation:
          ingress.hypyr.space/nodeport-approved="true"
        deny:
          conditions:
            all:
              # Block unless approval annotation is present
              - key: "{{ request.object.metadata.annotations.\"ingress.hypyr.space/nodeport-approved\" || 'false' }}"
                operator: NotEquals
                value: "true"

    # Rule 2: Approved NodePort must document justification
    - name: require-nodeport-justification
      match:
        any:
          - resources:
              kinds:
                - Service
              annotations:
                ingress.hypyr.space/nodeport-approved: "true"
      preconditions:
        all:
          - key: "{{ request.object.spec.type }}"
            operator: Equals
            value: NodePort
      validate:
        message: >-
          Service "{{ request.object.metadata.name }}" is approved for NodePort
          but missing required annotations:
          - ingress.hypyr.space/nodeport-network: "<VLAN/network>"
          - ingress.hypyr.space/nodeport-justification: "<reason>"
        pattern:
          metadata:
            annotations:
              ingress.hypyr.space/nodeport-approved: "true"
              ingress.hypyr.space/nodeport-network: "?*"
              ingress.hypyr.space/nodeport-justification: "?*"
